services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3306:3306'
    volumes:
      - ./db_mysql:/var/lib/mysql
      - ./init_mysql.sql:/docker-entrypoint-initdb.d/init.sql  # Script de inicialização do banco de dados
    command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  python-app:
    build: .
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
    volumes:
      - ./src:/app
    command: ["./wait-for-it.sh", "mysql:3306", "--", "python", "main.py"]
